### ISSUE TITLE
radar Chart - ReferenceError: Chart is not defined

### ISSUE THREAD

**Issue by Sartory** [adireddy/haxe-chart#2]
Hi there,
I tried to integrate the radarChart example into my form.
The problem is that this error always gets thrown:
`ReferenceError: Chart is not defined SystemImpl.hx:58
at ... 54:17`
53:`var ctx:CanvasRenderingContext2D = canvas.getContext("2d");`
54:` var radarChart = new Chart(ctx).Radar(data);`

I basically copied everything including the imports from the example here: [radarChart example](https://github.com/adireddy/haxe-chart/blob/master/samples/radar/Main.hx)
and the haxe-chart library is installed and also recognized by IDE (Visual Studio Code).

Does somebody has an idea what's wrong?

**Comment by Sartory** [comment]
Even just running the samples/radar/Main.hx I get 
`ReferenceError: Chart is not defined
Main.hx:78
    at new Main (.../source/Main.hx:78:3)
    at Function.Main.main (...source/Main.hx:90:3)
    at .../build/debug-html5/kha.js:31:7
    at .../build/debug-html5/kha.js:32:4`

**Comment by mjedmonds** [comment]
Did you happen to figure this out?

**Comment by Sartory** [comment]
Unfortunately I did not.
